version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-images-frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://api.ipasearchimage.id.vn
    restart: unless-stopped
    networks:
      - search-images-network

networks:
  search-images-network:
    external: true
