version: '3.8'

services:
  backend:
    build: .
    container_name: search-images-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - ./.env:/app/.env
    restart: unless-stopped
    networks:
      - search-images-network

networks:
  search-images-network:
    external: true 